site_name: 8iker_4n0n Security Research
site_description: Cybersecurity Research
site_author: 8iker_4n0n

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - search.highlight

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - tables

nav:
  - Home: index.md
  - IR Reports:
    - ir-reports/2026-06-27-polymorphic-webshell-ir.md
  - Malware Analysis:
    - malware-analysis/2026-06-27-polymorphic-webshell-analysis.md
